Repository awslabs/amazon-kinesis-video-streams-producer-sdk-cpp, pull requests merged in 2024-03, with the labels that each got.

#1151 remove unnecessary things from build
  .github/workflows/ci.yml
  CMake/Dependencies/libautoconf-CMakeLists.txt
  CMake/Dependencies/libautomake-CMakeLists.txt
  CMake/Dependencies/libcurl-CMakeLists.txt
  CMake/Dependencies/liblog4cplus-CMakeLists.txt
  CMake/Dependencies/libopenssl-CMakeLists.txt
  CMake/FindJsmn.cmake
  CMake/FindLog4cplus.cmake
  CMake/Utilities.cmake
  CMakeLists.txt
  samples/kvssink_gstreamer_sample.cpp
Labels: build, CI

#1131 CollectPadsStop to before parent state transition
  src/gstreamer/gstkvssink.cpp
Labels: gstreamer, Samples

#1144 Add PR description lint
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-desc-lint.yml
Labels: CI

#1158 Add quick-install instructions
  docs/linux.md
Labels: documentation
